travis:
  secure:
    BINSTAR_TOKEN: Stwy0kJUM0gW8qZZdJYKneaM39tVPH4zKwWTwaH4/otJ1FVJy19yGFpq50v0LUa2+8NQ4yrq4fm6UwCTE1i3jUPmlBwO5pbDy855FtokJxQzTUlnhse7lB/R06LgK66HQiAdG8aaeuQboanRaDe1S6BofrAavmdlJtO27T8cNYbql4iyY8CNgaHBLxf4tcPlR92yZGk11y5ekT1J4FgSLmdyDdeIXL1r6/5QZdbT0g1Wsd0YIif90JDLEjD8Nz9GAYuZcBQ3l+B6llBFrgw4WCcp17We/NZ3byQiqFtANapALQCQUZOO0bvHVm4pQ7qoFXfMunGOW4GSHo8PTvc4D/szug34CxDBy2zl6KXBoQhqWCSloYXVQQ7VMQNsLc8kzvxvpuXeDo+J52dZro44cnx/v6tZvXu42BYPiQV8zt1I3cW90H7s3SQ0eVO+cLo+2UQzMq1f+njbtOd9JYLerBShkJHVDtsS2s1tZE26+2zySCRnNHvJ2GrD4UuL+xX/4UC3VvoBOiRhOxPRqsyU7HCYz4c5uT5QkeLk0a7VBioIjk5eo8EjUtSwEYOSoU6Iw0NTBfjncyhHwqsFnqE1YKqrkE9otc7QwEiAK2QzO2TE/+wVS1hiiPkR1uj8xX/PNxlbHPH50oAwSz8OcL2bqHpqrTs7Tiphj5JeAW+5PNs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
