travis:
  secure:
    BINSTAR_TOKEN: at/wQf/ybf+CkGJgOFiLu0ZbkupOr13UUSmFhDxpbI8yh/8+ATmruhMNT1s+Kp6Y/ODWtp7hxGx6MNUGTFyKQwj9N14AUu6SAfomnwdRqoLiln0seRo190xnxAwTCC49GJ5rp9gaXtpwQA668XD1S9w1fjyz/qJw+2dNoET/nWINibiod0d0CHN1jeHVmqjOKoLWWl2AKh/V0h3AChai0/ls8MMG178ynLYPANdpQODUstS02jHYWdJlNEUTtjTzzc1XDvmVKHFfLDo55GUKxwEl40m7OBVldp6IFAbK/fgSM8550iynhMz5qeZtjD1X0tGfFOyZG9zEjrsFbv9GimVLMq1eanDbZc9QplTiYLFVgMr5Gim/bMSkr9QXWi75qNQqLa6kNwO7ntMD6UTL17RB4PGdlRDP5AFu9TdifcWC4wDC6bKUeJzbHRzHE9j6SSdKLMMUYotC7NR0susLXKUSn9mdg1dsng78Ir8bSOuv7h/7rTFMX1nuLiWNx/JIkCaVUXUkZ/wAFPVoHtTKWg5rgqifq+nrQbnMIIMVhGX0cqOI5KrZQyBZaoM8+S7aArrhQd1GMRxeB6CfjM+4kshKZXR6V94HMb7rTMi+KZdLMjLmf96u9XD0Lrtc6S1aRPoQS9OOKkEC+Hw7tcTdiVA8FmBLM8CH5QqKJYPTDmI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
